name: 'PROS Build Action'
description: 'Automatically build PROS templates'
branding:
  color: 'blue'
  icon: 'box'
  colorized: true

inputs:
  multithreading:
    required: false
    default: true
    description: Whether to use multithreading when building the project (-j flag in make)
  no_commit_hash:
    required: false
    default: false
    description: Whether to not include the commit hash in the artifact name
  copy_readme_and_license_to_include:
    required: false
    default: false
    description: Whether to copy the README.md and LICENSE files to the include directory
  lib_folder_name:
    required: false
    default: ''
    description: The name of the folder under the include directory that contains the headers for the project. Required if copy_readme_and_license_to_include is true
  write_job_summary:
    required: false
    default: true
    description: Whether to create a GitHub job summary

outputs:
  name:
    description: 'The recommended name for the artifact.'
    
runs:
  using: 'Docker'
  image: 'docker://ghcr.io/lemlib/pros-build:v2.0.1'
