name: Feature Request
description: Request a New Feature
title: '[FEATURE]: '
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem or missing capability
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: If you have a solution in mind, please describe it.
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: Have you considered any alternative solutions or workarounds?
  - type: textarea
    attributes:
      label: What's the Motivation for this request?
      description: How would this benefit users/maintainers?
